/********************************************
* FPUVM App: UVM for FPGAs
* Automatically generated by FPUVM Riviera App 
* Visit http://fp-uvm.blogspot.com for more 
* Generated on   : 2021-09-22 20:02:27
********************************************/ 


// Generating SystemVerilog interface for module: avl_flash
// ---------------------------------------------------------
interface avl_flash_if (input logic clock);
  logic   avmm_addr;
  logic   avmm_read;
  logic   avmm_write;
  logic  [31:0] avmm_writedata;
  logic  [9:0] csr_status;
  logic   reset_n;
  logic  [31:0] avmm_readdata;
  logic  [31:0] csr_control;
  // End of interface signals 


  // Start of clocking block definition 
  clocking drv_cb @(posedge clock);
    output avmm_addr;
    output avmm_read;
    output avmm_write;
    output avmm_writedata;
    output csr_status;
    output reset_n;
    input avmm_readdata;
    input csr_control;
  endclocking : drv_cb
  // End of clocking block definition 
  
  clocking mon_cb @(posedge clock);
    input avmm_addr;
    input avmm_read;
    input avmm_write;
    input avmm_writedata;
    input csr_status;
    input reset_n;
    input avmm_readdata;
    input csr_control;
  endclocking : mon_cb
  // End of clocking block definition 

  // Start of init_signals task 

  task init_signals ();
    drv_cb.avmm_addr <= 0;
    drv_cb.avmm_read <= 0;
    drv_cb.avmm_write <= 0;
    drv_cb.avmm_writedata <= 0;
    drv_cb.csr_status <= 0;
    drv_cb.reset_n <= 0;
  endtask : init_signals

endinterface : avl_flash_if
