/********************************************
* FPUVM App: UVM for FPGAs
* Automatically generated by FPUVM Riviera App 
* Visit http://fp-uvm.blogspot.com for more 
* Generated on   : 2021-09-22 20:02:27
********************************************/ 


// Generating FPUVM Test for module: avl_flash
// ---------------------------------------------------------

// Automatically generated from FPUVM app 
// Thanks for using FPUVM see http://fp-uvm.blogspot.com for more

import uvm_pkg::*;
`include "fp_uvm_macros.svh"
// Import FPUVM Package
import fp_uvm_pkg::*;

// Use the base class provided by the FPUVM
class avl_flash_test extends fp_uvm_base_test;
  // Create a handle to the actual interface

  virtual avl_flash_if vif;
  task reset;
     `fp_uvm_display ("Start of reset")
     `fp_uvm_display ("Fill in your reset logic here ")
     this.vif.drv_cb.reset_n <= 1'b0;
     this.vif.init_signals();
     repeat (5) @ (this.vif.drv_cb);
     this.vif.drv_cb.reset_n <= 1'b1;
     repeat (1) @ (this.vif.drv_cb);
    `fp_uvm_display ("End of reset")
  endtask : reset

  task main ();
    `fp_uvm_display ("Start of main", UVM_MEDIUM)
    `fp_uvm_display ("Fill in your main logic here ")
    // this.vif.drv_cb.inp_1 <= 1'b0;
    // this.vif.drv_cb.inp_2 <= 'haa;
    repeat (50) @ (this.vif.drv_cb);
    `fp_uvm_display ("End of main")
  endtask : main

endclass : avl_flash_test

